name: 'Run Tests'

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        run: npm install

  test-ts:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: 'Test TS'
        run: npm run build:ts

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: 'Lint'
        run: npm run lint

  test-unit:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: 'Run Unit Tests'
        run: npm run test:run
