name: 'Run Tests'

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        run: npm install
      - name: 'Lint'
        run: npm run lint
      - name: 'Run Unit Tests'
        run: npm run test:run
      - name: 'Install Browsers'
        run: npm run test:e2e:install
      - name: 'Run E2E Tests'
        run: npm run test:e2e
