name: 'Run E2E Tests'

on:
  push:
    tags:
      - '*'

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install'
        run: npm install
      - name: 'Install Browsers'
        run: npm run test:e2e:install
      - name: 'Run E2E Tests'
        run: npm run test:e2e
